# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

baseurl: "" # the subpath of your site, e.g. /blog
url: https://jaumebarber.com # the base hostname & protocol for your site, e.g. http://example.com
github_repo: jaumebarber.github.io # the GitHub repo name for your project
github_username: jaumebarber

# Optional social links, you can choose from the following options:
# linkedin (default), bluesky, x (twitter), instagram, medium, or dribbble just add
# the name of the media + _username e.g. medium_username and then add your user name
# to make it appear on the page
user_name: Jaume Barber
user_email: jbarber@hipervincle.com
linkedin_username: jaumebarber
bluesky_username: jaumebarber.bsky.social

languages: ["en", "ca", "es", "it"]
langsep: ·
default_lang: en
exclude_from_localization: ["javascript", "images", "css", "public", "sitemap", "assets"]
parallel_localization: false

# Build settings
markdown: kramdown

# Remote settings
repository: broccolini/swiss
livereload: true
port: 8080

include: ["_pages"]
exclude: ["bin", "Dockerfile", "compose.yml"]

plugins:
  - jekyll-polyglot
  - jekyll-octicons
  - jekyll-redirect-from
  - jekyll-minifier

redirect_from:
  json: false

jekyll-minifier:
  uglifier_args:
    harmony: true
# TODO: fix mobile header menu white area view
# TODO: implement print media query
# TODO: try whether Dockerfile and compose.yml work
# TODO: try text animations in title text
# TODO: make some posts to fill the page a bit
# TODO: add a print resume button
# TODO: explore the gem creation for helvetic resume theme
# TODO: adapt the README.md
# TODO: add a favicon
# TODO: add a sitemap.xml
# TODO: try more plugins
# TODO: develop a system not to upload artifacts whenever non src code is changed
