source "https://rubygems.org"
gemspec

gem "wdm", ">= 0.1.0" if Gem.win_platform?
gem "bundler", "~> 2.6.5"
gem "faraday-retry", "~> 2.2"
gem "ostruct", "~> 0.6.1"
gem "fiddle", "~> 1.1.6"
gem "bigdecimal"
gem "logger"
gem "jekyll", "~> 4.4.1"
gem "uglifier", "~> 4.2.1"

