# Lighthouse-Badger-Default | GitHub Action Workflow
# 
# Description: Generates, adds & updates manually/automatically Lighthouse badges & reports from one/multiple input URL(s) to a selected target repository & branch
# Author: Sitdisch
# Source: https://github.com/myactionway/lighthouse-badger-workflows
# License: MIT
# Copyright (c) 2021 Sitdisch

name: 'Lighthouse Badger'

########################################################################
# DEFINE YOUR INPUTS AND TRIGGERS IN THE FOLLOWING
########################################################################

# INPUTS as environmental variables (env) for not manually triggered workflows 
env:
  URLS: https://jaumebarber.com # URL(s) to be checked e.g. 'https://github.com/sitdisch https://github.com/mythemeway'
  TOKEN_NAME: LIGHTHOUSE_BADGER_TOKEN # target token name; insert only the name never the real value e.g. 'LIGHTHOUSE_BADGER_TOKEN'
  REPOSITORY: ${{ github.repository }}
  BRANCH: master
  BADGES_ARGS: '-b pagespeed -o lighthouse_results -r'
  AUDIT_TYPE: 'both'
  MOBILE_LIGHTHOUSE_PARAMS: '--only-categories=performance,accessibility,best-practices,seo --throttling.cpuSlowdownMultiplier=2'
  DESKTOP_LIGHTHOUSE_PARAMS: '--only-categories=performance,accessibility,best-practices,seo --preset=desktop --throttling.cpuSlowdownMultiplier=1'
  USER_NAME: Jaume Barber
  USER_EMAIL: jbarber@hipervincle.com
  COMMIT_MESSAGE: "test: add Lighthouse results and badges"
# TRIGGERS
on:
  schedule:
    - cron: "45 21 * * 4"
  
  # THAT'S IT; YOU'RE DONE;
  workflow_dispatch:

########################################################################
# THAT'S IT; YOU DON'T HAVE TO DEFINE ANYTHING IN THE FOLLOWING
########################################################################

jobs:
  lighthouse-badger:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - name: Checkout ${{ github.repository }} 🛎️
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REPOSITORY || github.repository }}
          token: ${{ secrets[env.TOKEN_NAME] }} 
          ref: ${{ env.BRANCH }}
      - name: Checkout myactionway/lighthouse-badges 🛎️
        uses: actions/checkout@v4
        with:
          repository: 'myactionway/lighthouse-badges'
          path: temp_lighthouse_badges_nested
      - name: Retrieve Lighthouse badges 🛡️
        uses: myactionway/lighthouse-badger-action@v2.2
        with:
          urls: ${{ env.URLS }}
          badges_args: ${{ env.BADGES_ARGS }}
          audit_type: ${{ env.AUDIT_TYPE }}
          mobile_lighthouse_params: ${{ env.MOBILE_LIGHTHOUSE_PARAMS }}
          desktop_lighthouse_params: ${{ env.DESKTOP_LIGHTHOUSE_PARAMS }}
          user_name: ${{ env.USER_NAME }}
          user_email: ${{ env.USER_EMAIL }}
          commit_message: ${{ env.COMMIT_MESSAGE }}
          max_push_attempts: 5