name: Run Prettier

on:
  workflow_call:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.repository }} 🧾
        uses: actions/checkout@v4
      - name: Install Yarn 🧶
        uses: Borales/actions-yarn@v5.0.0
        with:
          cmd: install
      - name: Prettier Check 🔎
        id: prettier
        run: | 
          npx prettier src --check || echo "needs_formatting=true" >> $GITHUB_OUTPUT
          exit 0  # Prevent the step from failing the pipeline
      - name: Run Prettier 🦋
        # https://docs.github.com/en/actions/learn-github-actions/expressions#failure
        if: ${{  steps.prettier.outputs.needs_formatting == 'true' }}
        run: |
          npx prettier src --write
      - name: Commit and push changes ⬆️
        if: ${{  steps.prettier.outputs.needs_formatting == 'true' }}
        run: |
          git config user.name "Jaume Barber"
          git config user.email "jbarber@hipervincle.com"
          git add -A
          git commit -m "style: format code with Prettier"
          git push